workshop_django_project/fruitipediaApp/fruitipediaApp/fruits/urls.py
from django.urls import path, include
from fruitipediaApp.fruits import views

urlpatterns = (
    path('', views.index, name="index"),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create-category/', views.create_category, name='create_category'),
    path('create-fruit/', views.CreateFruitView.as_view(), name='create_fruit'),
    path('<int:pk>/', include([
        path('edit-fruit/', views.edit_view, name='edit_fruit'),
        path('delete-fruit/', views.DeleteFruitView.as_view(), name='delete_fruit'),
        path('details-fruit/', views.details_view, name='details_fruit'),
    ]))
)

workshop_django_project/fruitipediaApp/fruitipediaApp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fruitipediaApp.fruits.urls')),
]

workshop_django_project/fruitipediaApp/fruitipediaApp/fruits/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from fruitipediaApp.fruits.validators import OnlyLettersValidator


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        unique=True,
        null=False,
        blank=False,
    )

    def __str__(self):
        return self.name


class Fruit(models.Model):
    name = models.CharField(
        max_length=30,
        unique=True,
        null=False,
        blank=False,
        validators=[
            MinLengthValidator(2),
            OnlyLettersValidator()
        ]
    )

    image_url = models.URLField(
        null=False,
        blank=False,
    )

    description = models.TextField(
        null=False,
        blank=False,
    )

    nutrition = models.TextField(
        null=True,
        blank=True,
    )

    category = models.ForeignKey(
        to=Category,
        on_delete=models.CASCADE,
        null=True
    )

workshop_django_project/fruitipediaApp/fruitipediaApp/fruits/forms.py
from django import forms
from fruitipediaApp.fruits.models import Category, Fruit


class CategoryBaseForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = "__all__"
        widgets = {'name': forms.TextInput(attrs={'placeholder': 'Category name', }), }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].label = ''


class CategoryAddForm(CategoryBaseForm):
    pass


class BaseFruitForm(forms.ModelForm):
    class Meta:
        model = Fruit
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Fruit name', }),
            'description': forms.TextInput(attrs={'placeholder': 'Enter the description', }),
            'image_url': forms.URLInput(attrs={'placeholder': 'Enter the url for the image', }),
            'nutrition': forms.NumberInput(attrs={'placeholder': 'Enter the fruit nutrition', }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].label = ''


class AddFruitForm(BaseFruitForm):
    pass


class EditFruitForm(BaseFruitForm):
    pass


class DeleteFruitForm(BaseFruitForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.disabled = True

workshop_django_project/fruitipediaApp/fruitipediaApp/fruits/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView

from fruitipediaApp.fruits.forms import CategoryAddForm, AddFruitForm, EditFruitForm, DeleteFruitForm
from fruitipediaApp.fruits.models import Fruit


def index(request):
    return render(request, 'common/index.html')


def dashboard(request):
    fruits = Fruit.objects.all()

    context = {
        "fruits": fruits,
    }

    return render(request, 'common/dashboard.html', context)


class CreateFruitView(CreateView):
    model = Fruit
    form_class = AddFruitForm
    template_name = 'fruits/create-fruit.html'
    success_url = reverse_lazy('dashboard')


def edit_view(request, pk):
    fruit = Fruit.objects.get(pk=pk)

    if request.method == "GET":
        form = EditFruitForm(instance=fruit)
    else:
        form = EditFruitForm(request.POST, instance=fruit)

        if form.is_valid():
            form.save()
            return redirect('dashboard')
        # fruit.delete() for delete FBV

    context = {
        "fruit": fruit,
        "form": form,
    }

    return render(request, 'fruits/edit-fruit.html', context)


def details_view(request, pk):
    fruit = Fruit.objects.get(pk=pk)

    context = {
        "fruit": fruit
    }

    return render(request, 'fruits/details-fruit.html', context)


class DeleteFruitView(DeleteView):
    model = Fruit
    form_class = DeleteFruitForm
    template_name = 'fruits/delete-fruit.html'
    success_url = reverse_lazy('dashboard')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object)
        return self.render_to_response(self.get_context_data(form=form, object=self.object))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.success_url)


def create_category(request):
    if request.method == "GET":
        form = CategoryAddForm()
    else:  # if post
        form = CategoryAddForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('dashboard')

    context = {
        "form": form,
    }

    return render(request, 'categories/create-category.html', context)

workshop_django_project/fruitipediaApp/templates/categories/create-category.html
{% extends 'common/base.html' %}

{% block content %}
    <section id="create">
        <div class="form">
            <h2>Add Category</h2>
            <form class="create-form" action="{% url 'create_category' %}" method="POST">
                {{ form }}
                {% csrf_token %}
                <button type="submit">Add Category</button>
            </form>
        </div>
    </section>
{% endblock %}

workshop_django_project/fruitipediaApp/templates/common/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="{% url 'index' %}">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo"/>
        </a>

        <nav>
            <div class="nav-items">
                <a href="{% url 'create_category' %}">Create Category</a>
                <a href="{% url 'create_fruit' %}">Create Fruit</a>
                <a href="{% url 'dashboard' %}">Dashboard</a>
            </div>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2024. All rights reserved.</p>
</footer>
</body>
</html>

workshop_django_project/fruitipediaApp/templates/common/dashboard.html
{% extends 'base.html' %}

{% block content %}
{% if fruits %}
    <h2>Fruits</h2>
    <section id="dashboard">
    {% for fruit in fruits %}
        <div class="fruit">
            <img src="{{ fruit.image_url }}" alt="example1"/>
            <h3 class="title">{{ fruit.name }}</h3>
            <p class="description">{{ fruit.description|truncatechars:15 }}</p>
            <a class="details-btn" href="#">More Info</a>
        </div>
    {% endfor %}
    </section>
{% else %}
    <h2>No fruit info yet.</h2>
{% endif %}
    
{% endblock %}

workshop_django_project/fruitipediaApp/templates/common/index.html
{% extends 'common/base.html' %}

{% block content %}
    <section id="home">
        <h1>Learn more about your favorite fruits</h1>
        <img
                src="/static/images/pexels-pixabay-161559-dImkWBDHz-transformed (1).png"
                alt="home"
        />

    </section>
{% endblock %}

workshop_django_project/fruitipediaApp/templates/fruits/create-fruit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="/static/styles/styles.css"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="">
            <img id="logo-img" src="/static/images/logo.png" alt="logo"/>
        </a>

        <nav>
            <div class="nav-items">
                <a href="#">Create Category</a>
                <a href="#">Create Fruit</a>
                <a href="#">Dashboard</a>
            </div>
        </nav>{% extends 'common/base.html' %}

{% block content %}
<section id="create">
    <div class="form">
        <h2>Add Fruit</h2>
        <form class="create-form" method="POST" action="{% url 'create_fruit' %}">
            {{ form }}
            {% csrf_token %}
            <button type="submit">Add Fruit</button>
        </form>
    </div>
</section>
{% endblock %}
    </header>

    <main>
        <!-- Add Fruit Form -->
        <section id="create">
            <div class="form">
                <h2>Add Fruit</h2>
                <form class="create-form">
                    <input
                            type="text"
                            name="name"
                            id="name"
                            placeholder="Fruit Name"
                    />
                    <input
                            type="text"
                            name="imageUrl"
                            id="Fruit-image"
                            placeholder="Fruit Image URL"
                    />
                    <textarea
                            id="fruit-description"
                            name="description"
                            placeholder="Fruit Description"
                            rows="10"
                            cols="50"
                    ></textarea>
                    <textarea
                            id="fruit-nutrition"
                            name="nutrition"
                            placeholder="Nutrition Info"
                            rows="10"
                            cols="50"
                    ></textarea>
                    <select name="category" required="" id="id_category">
                        <option value="" selected="">Relate Category</option>

                        <option value="1">edible fruit</option>

                    </select>
                    <button type="submit">Add Fruit</button>
                </form>
            </div>
        </section>
    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

workshop_django_project/fruitipediaApp/templates/fruits/delete-fruit.html
{% extends 'common/base.html' %}

{% block content %}
<section id="edit">

    <div class="form">
        <h2>Delete Fruit</h2>

        <form class="edit-form" method="post" action="{% url 'delete_fruit' object.pk %}">
            {{ form }}
            {% csrf_token %}

            <button type="submit">Delete</button>
        </form>
    </div>

</section>
{% endblock %}

workshop_django_project/fruitipediaApp/templates/fruits/details-fruit.html
{% extends 'common/base.html' %}

{% block content %}
<section id="details">
    <div id="details-wrapper">
        <!-- fruit image -->
        <img
                id="details-img"
                src="{{ fruit.image_url }}"
                alt="example1"
        />
        <!-- fruit name -->
        <p id="details-title">Name: {{ fruit.name }}</p>
        <div id="info-wrapper">
            <div id="details-description">
                <p id="category">Category: {{ fruit.category.name }}</p>
                <!-- fruit description -->
                <p>
                   {{ fruit.description }}
                </p>
                <!-- fruit nutrition -->
                <p id="nutrition">Nutrition</p>
                <!-- fruit nutrition details -->
                <p id="details-nutrition">
                    {{ fruit.nutrition }}
                </p>
            </div>

            <!--Edit and Delete buttons -->
            <div id="action-buttons">
                <a href="{% url 'edit_fruit' fruit.pk %}" id="edit-btn">Edit</a>
                <a href="{% url 'delete_fruit' fruit.pk %}" id="delete-btn">Delete</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

workshop_django_project/fruitipediaApp/templates/fruits/edit-fruit.html
{% extends 'common/base.html' %}

{% block content %}
<section id="edit">
    <div class="form">
        <h2>Edit Fruit</h2>
        <form class="edit-form" method="post" action="{% url 'edit_fruit' fruit.pk %}">
            {{ form }}
            {% csrf_token %}
            <button type="submit">Edit</button>
        </form>
    </div>
</section>
{% endblock %}